version: 2
project_name: moley

before: 
  hooks:
    - go mod tidy

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/stupside/moley/v2/internal/version.Commit={{.Commit}}'
      - -X 'github.com/stupside/moley/v2/internal/version.BuildTime={{.Date}}'
      - -X 'github.com/stupside/moley/v2/internal/version.Version={{.Version}}'
    binary: moley

dockers:
  - image_templates:
      - "ghcr.io/stupside/moley:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.description=Expose your local apps to the world—securely, instantly, and with zero hassle."
      - "--label=org.opencontainers.image.documentation={{.GitURL}}/blob/main/README.md"

  - image_templates:
      - "ghcr.io/stupside/moley:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.url={{.GitURL}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.description=Expose your local apps to the world—securely, instantly, and with zero hassle."
      - "--label=org.opencontainers.image.documentation={{.GitURL}}/blob/main/README.md"

docker_manifests:
  - name_template: "ghcr.io/stupside/moley:{{ .Version }}"
    image_templates:
      - "ghcr.io/stupside/moley:{{ .Version }}-amd64"
      - "ghcr.io/stupside/moley:{{ .Version }}-arm64"
  - name_template: "ghcr.io/stupside/moley:latest"
    image_templates:
      - "ghcr.io/stupside/moley:{{ .Version }}-amd64"
      - "ghcr.io/stupside/moley:{{ .Version }}-arm64"

changelog:
  sort: asc
  use: git
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/stupside/moley/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

homebrew_casks:
  - name: moley
    description: "Expose your local apps to the world—securely, instantly, and with zero hassle."
    commit_author:
      name: moley
      email: git@moley.dev
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    zap:
      trash:
        - "~/.moley/config.yml"
      delete:
        - "~/.moley/config.yml"
    repository:
      name: "homebrew-tap"
      owner: "stupside"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"