version: 2
project_name: moley

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'moley/internal/version.Commit={{.Commit}}'
      - -X 'moley/internal/version.BuildTime={{.Date}}'
      - -X 'moley/internal/version.Version={{.Version}}'
    binary: moley

changelog:
  sort: asc
  use: git
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/stupside/moley/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

homebrew_casks:
  - name: moley
    description: "Expose your local apps to the world—securely, instantly, and with zero hassle."
    commit_author:
      name: moley
      email: git@moley.dev
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    zap:
      trash:
        - "~/.moley/config.yml"
      delete:
        - "~/.moley/config.yml"
    repository:
      name: "homebrew-tap"
      owner: "stupside"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"