version: '3'

vars:
  BINARY_NAME: moley
  VERSION:
    sh: git describe --tags --always --dirty
  COMMIT:
    sh: git rev-parse --short HEAD
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  LDFLAGS: -ldflags "-X 'github.com/stupside/moley/v2/internal/version.Version={{.VERSION}}' -X 'github.com/stupside/moley/v2/internal/version.Commit={{.COMMIT}}' -X 'github.com/stupside/moley/v2/internal/version.BuildTime={{.BUILD_TIME}}'"

tasks:
  
  clean: 
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - cloudflared tunnel list --output json | jq -r '.[].id' | xargs -n1 -I{} cloudflared tunnel delete {}

  # Go build tasks
  go:build:
    desc: Build the application
    cmds:
      - go build {{.LDFLAGS}} -o {{.BINARY_NAME}} .

  # Docker tasks
  docker:moley:
    desc: Run moley commands in Docker (pass args after --)
    cmds:
      - docker compose run --rm moley {{.CLI_ARGS}}

  docker:cloudflared:
    desc: Run cloudflared commands in Docker (pass args after --)
    cmds:
      - docker compose run --rm --entrypoint cloudflared moley {{.CLI_ARGS}}